#!/bin/bash

# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xeuo pipefail

if [ $# -lt 4 ]; then
  echo "Usage: $0 <pretrain_gpt_path> <mixture_script> <work_path> <tokenizer_model> [pretrained_model_path]"
  exit 1
fi

# Auto-detect the number of visible GPUs. Honor CUDA_VISIBLE_DEVICES when set,
# otherwise fall back to nvidia-smi (which lists all physical GPUs on the host).
if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
    NUM_GPUS=$(echo "$CUDA_VISIBLE_DEVICES" | tr ',' '\n' | grep -c .)
else
    NUM_GPUS=$(nvidia-smi -L | wc -l)
fi

# Path to Megatron-LM's pretrain_gpt.py script
PRETRAIN_GPT_PATH=$1

# Path to a data mixture generated by the 5_mixture.py script, e.g., n1.sh
MIXTURE_SCRIPT=$2
readarray -t MIXTURE_LINES < <(bash "$MIXTURE_SCRIPT")
DATA_ARGS=()
for line in "${MIXTURE_LINES[@]}"; do
    DATA_ARGS+=($line)
done

# Path to save the checkpoints, etc. for the proxy model
# Follow the naming convention of megatron_exp/n{i} to match the proxy model name to its mixture script
WORK_PATH=$3
CHECKPOINT_PATH="${WORK_PATH}/checkpoint"
TENSORBOARD_LOGS_PATH="${WORK_PATH}/tensorboard"
DATA_CACHE_PATH="${WORK_PATH}/data_cache"
mkdir -p "$CHECKPOINT_PATH" "$TENSORBOARD_LOGS_PATH" "$DATA_CACHE_PATH"

# Path to the tokenizer model file, e.g., tokenizer.model
TOKENIZER_MODEL=$4

# Optional 5th argument: checkpoint path to a pretrained model to fine-tune from.
# If set, pass --load <pretrained> --finetune. If omitted, --load points at
# CHECKPOINT_PATH so the run starts from scratch (and naturally resumes from
# saved checkpoints on restart). ${5:-} keeps `set -u` happy when unset.
PRETRAINED_MODEL_PATH="${5:-}"

LOAD_ARGS=()
if [ -n "$PRETRAINED_MODEL_PATH" ]; then
    if [ ! -d "$PRETRAINED_MODEL_PATH" ]; then
        echo "Pretrained model path does not exist: $PRETRAINED_MODEL_PATH" >&2
        exit 1
    fi
    LOAD_ARGS+=(--load "$PRETRAINED_MODEL_PATH" --finetune)
else
    LOAD_ARGS+=(--load "$CHECKPOINT_PATH")
fi

export NCCL_DEBUG=INFO

# TIPS AND CONSIDERATIONS:
#
# If using a pretrained model, make sure to set parameters like --num-layers, --hidden-size, --num-attention-heads,
# --max-position-embeddings, --tokenizer-type, --tokenizer-model, etc. appropriately
#
# Note small --train-iters 10000 for proxy model training
# Consider increasing --train-iters depending on your GPU setup and throughput, but
# don't forget that this will impact the learning rate schedule
#
# Evaluation is disabled by default, but can be enabled by setting --eval-iters > 0 and a reasonably small --eval-interval
# Note: --eval-interval 50000000 is used below to avoid a zero division error, it's set to a large value so eval never triggers
#
# Consider lowering --lr for less noise, e.g., --lr 3e-4, if noisy training is observed
#
# Make sure NUM_GPUS, --global-batch-size, and --micro-batch-size align with each other
# That is, global-batch-size = micro-batch-size x data-parallel-size x gradient-accumulation-steps
# Example: if NUM_GPUS = 8
#          and if tensor-model-parallel-size = 1, pipeline-model-parallel-size = 1, micro-batch-size = 64, and global-batch-size = 4096
#          then data-parallel-size = 8
#          and 4096 / (64 x 8) = 8
#          and gradient-accumulation-steps = 8
# The default values will work fine for any value of NUM_GPUS that is a power of 2
# Else, adjust the value of global-batch-size, etc. to fit the formula above
#
# Decreasing the micro-batch-size can help reduce memory pressure, e.g., --micro-batch-size 32
#
# For the best performing mixtures, consider re-running with a new seed to verify the model isn't a seed-specific artifact

torchrun --nproc_per_node $NUM_GPUS "$PRETRAIN_GPT_PATH" \
    --num-layers 12 \
    --hidden-size 1344 \
    --num-attention-heads 12 \
    --tensor-model-parallel-size 1 \
    --pipeline-model-parallel-size 1 \
    --seq-length 1024 \
    --max-position-embeddings 1024 \
    --micro-batch-size 64 \
    --global-batch-size 4096 \
    --train-iters 10000 \
    --optimizer adam \
    --weight-decay 0.1 \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --init-method-std 0.006 \
    --clip-grad 1.0 \
    --bf16 \
    --distributed-timeout-minutes 120 \
    --auto-detect-ckpt-format \
    --exit-duration-in-mins 110 \
    --override-opt_param-scheduler \
    --lr-decay-style cosine \
    --lr 5e-4 \
    --min-lr 1.0e-5 \
    --lr-warmup-fraction .01 \
    --lr-decay-iters 10000 \
    --seed 1234 \
    --train-data-path "${DATA_ARGS[@]}" \
    --tokenizer-type Llama2Tokenizer \
    --tokenizer-model "$TOKENIZER_MODEL" \
    --data-cache-path "$DATA_CACHE_PATH" \
    --dataloader-type cyclic \
    --log-interval 100 \
    --save-interval 1000 \
    --eval-interval 50000000 \
    --save "$CHECKPOINT_PATH" \
    "${LOAD_ARGS[@]}" \
    --eval-iters 0 \
    --tensorboard-dir "$TENSORBOARD_LOGS_PATH"
